apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-ssm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::689505382884:role/eks-ssm-ps-prod-role

---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  serviceAccountName: oidc-ssm
  containers:
    - name: demo
      image: 689505382884.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-store
      imagePullPolicy: Always
      env:
        - name: PARAMS
          value: "prod.payment.cart_port prod.payment.user_port prod.payment.cart_host"
---